2025-05-08 10:11:41,227 - telethon.network.mtprotosender - INFO - Connecting to 149.154.167.51:443/TcpFull...
2025-05-08 10:11:43,410 - telethon.network.mtprotosender - INFO - Connection to 149.154.167.51:443/TcpFull complete!
2025-05-08 10:11:44,447 - telethon.client.users - INFO - Phone migrated to 4
2025-05-08 10:11:44,447 - telethon.client.telegrambaseclient - INFO - Reconnecting to new data center 4
2025-05-08 10:11:44,577 - telethon.network.mtprotosender - INFO - Disconnecting from 149.154.167.51:443/TcpFull...
2025-05-08 10:11:44,578 - telethon.network.mtprotosender - INFO - Disconnection from 149.154.167.51:443/TcpFull complete!
2025-05-08 10:11:44,578 - telethon.network.mtprotosender - INFO - Connecting to 149.154.167.92:443/TcpFull...
2025-05-08 10:11:45,761 - telethon.network.mtprotosender - INFO - Connecting to 149.154.167.92:443/TcpFull...
2025-05-08 10:11:47,334 - telethon.network.mtprotosender - INFO - Connection to 149.154.167.92:443/TcpFull complete!
2025-05-08 10:13:18,274 - telethon.network.mtprotosender - INFO - Connecting to 149.154.167.51:443/TcpFull...
2025-05-08 10:13:19,667 - telethon.network.mtprotosender - INFO - Connection to 149.154.167.51:443/TcpFull complete!
2025-05-08 10:13:20,121 - telethon.client.users - INFO - Phone migrated to 4
2025-05-08 10:13:20,230 - telethon.client.telegrambaseclient - INFO - Reconnecting to new data center 4
2025-05-08 10:13:20,340 - telethon.network.mtprotosender - INFO - Disconnecting from 149.154.167.51:443/TcpFull...
2025-05-08 10:13:20,341 - telethon.network.mtprotosender - INFO - Disconnection from 149.154.167.51:443/TcpFull complete!
2025-05-08 10:13:20,342 - telethon.network.mtprotosender - INFO - Connecting to 149.154.167.92:443/TcpFull...
2025-05-08 10:13:21,807 - telethon.network.mtprotosender - INFO - Connection to 149.154.167.92:443/TcpFull complete!
2025-05-08 10:13:44,403 - telethon.network.mtprotosender - INFO - Disconnecting from 149.154.167.92:443/TcpFull...
2025-05-08 10:13:44,408 - telethon.network.mtprotosender - INFO - Disconnection from 149.154.167.92:443/TcpFull complete!
2025-05-08 10:14:42,646 - telethon.network.mtprotosender - INFO - Connecting to 149.154.167.92:443/TcpFull...
2025-05-08 10:14:42,749 - telethon.network.mtprotosender - INFO - Connection to 149.154.167.92:443/TcpFull complete!
2025-05-08 10:20:56,900 - telethon.network.mtprotosender - INFO - Connecting to 149.154.167.92:443/TcpFull...
2025-05-08 10:20:57,003 - telethon.network.mtprotosender - INFO - Connection to 149.154.167.92:443/TcpFull complete!
2025-05-08 10:23:20,870 - telethon.network.mtprotosender - INFO - Connecting to 149.154.167.92:443/TcpFull...
2025-05-08 10:23:20,973 - telethon.network.mtprotosender - INFO - Connection to 149.154.167.92:443/TcpFull complete!
2025-05-08 10:23:24,855 - telethon.network.mtprotosender - INFO - Connecting to 149.154.167.92:443/TcpFull...
2025-05-08 10:23:24,958 - telethon.network.mtprotosender - INFO - Connection to 149.154.167.92:443/TcpFull complete!
2025-05-08 10:23:46,181 - telethon.network.mtprotosender - INFO - Connecting to 149.154.167.92:443/TcpFull...
2025-05-08 10:23:46,284 - telethon.network.mtprotosender - INFO - Connection to 149.154.167.92:443/TcpFull complete!
2025-05-08 10:23:47,233 - telethon.network.mtprotosender - INFO - Disconnecting from 149.154.167.92:443/TcpFull...
2025-05-08 10:23:47,236 - telethon.network.mtprotosender - INFO - Disconnection from 149.154.167.92:443/TcpFull complete!
2025-05-08 10:23:57,378 - telethon.network.mtprotosender - INFO - Connecting to 149.154.167.92:443/TcpFull...
2025-05-08 10:23:57,482 - telethon.network.mtprotosender - INFO - Connection to 149.154.167.92:443/TcpFull complete!
2025-05-08 10:24:35,581 - __main__ - ERROR - Error validating session: Incorrect padding
2025-05-08 10:24:56,261 - telethon.network.mtprotosender - INFO - Connecting to 149.154.167.92:443/TcpFull...
2025-05-08 10:24:56,364 - telethon.network.mtprotosender - INFO - Connection to 149.154.167.92:443/TcpFull complete!
2025-05-08 10:24:57,290 - telethon.network.mtprotosender - INFO - Disconnecting from 149.154.167.92:443/TcpFull...
2025-05-08 10:24:57,293 - telethon.network.mtprotosender - INFO - Disconnection from 149.154.167.92:443/TcpFull complete!
2025-05-08 10:28:16,710 - telethon.network.mtprotosender - INFO - Connecting to 149.154.167.92:443/TcpFull...
2025-05-08 10:28:16,812 - telethon.network.mtprotosender - INFO - Connection to 149.154.167.92:443/TcpFull complete!
2025-05-08 10:28:51,825 - telethon.network.mtprotosender - INFO - Connecting to 149.154.167.92:443/TcpFull...
2025-05-08 10:28:51,928 - telethon.network.mtprotosender - INFO - Connection to 149.154.167.92:443/TcpFull complete!
2025-05-08 10:28:56,985 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-5' coro=<MTProtoSender._send_loop() running at /home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/telethon/network/mtprotosender.py:464> wait_for=<Future pending cb=[Task.task_wakeup()]>>
2025-05-08 10:28:56,985 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-6' coro=<MTProtoSender._recv_loop() running at /home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/telethon/network/mtprotosender.py:507> wait_for=<Future pending cb=[Task.task_wakeup()]>>
2025-05-08 10:28:56,986 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-3' coro=<Connection._send_loop() running at /home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/telethon/network/connection/connection.py:322> wait_for=<Future pending cb=[Task.task_wakeup()]>>
2025-05-08 10:28:56,986 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-4' coro=<Connection._recv_loop() running at /home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/telethon/network/connection/connection.py:341> wait_for=<Future pending cb=[Task.task_wakeup()]>>
2025-05-08 10:29:00,193 - telethon.network.mtprotosender - INFO - Connecting to 149.154.167.92:443/TcpFull...
2025-05-08 10:29:00,298 - telethon.network.mtprotosender - INFO - Connection to 149.154.167.92:443/TcpFull complete!
2025-05-08 10:29:05,346 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-5' coro=<MTProtoSender._send_loop() running at /home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/telethon/network/mtprotosender.py:464> wait_for=<Future pending cb=[Task.task_wakeup()]>>
2025-05-08 10:29:05,347 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-6' coro=<MTProtoSender._recv_loop() running at /home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/telethon/network/mtprotosender.py:507> wait_for=<Future pending cb=[Task.task_wakeup()]>>
2025-05-08 10:29:05,347 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-3' coro=<Connection._send_loop() running at /home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/telethon/network/connection/connection.py:322> wait_for=<Future pending cb=[Task.task_wakeup()]>>
2025-05-08 10:29:05,347 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-4' coro=<Connection._recv_loop() running at /home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/telethon/network/connection/connection.py:341> wait_for=<Future pending cb=[Task.task_wakeup()]>>
2025-05-08 10:29:06,258 - telethon.network.mtprotosender - INFO - Connecting to 149.154.167.92:443/TcpFull...
2025-05-08 10:29:06,361 - telethon.network.mtprotosender - INFO - Connection to 149.154.167.92:443/TcpFull complete!
2025-05-08 10:29:11,397 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-5' coro=<MTProtoSender._send_loop() running at /home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/telethon/network/mtprotosender.py:464> wait_for=<Future pending cb=[Task.task_wakeup()]>>
2025-05-08 10:29:11,397 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-6' coro=<MTProtoSender._recv_loop() running at /home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/telethon/network/mtprotosender.py:507> wait_for=<Future pending cb=[Task.task_wakeup()]>>
2025-05-08 10:29:11,397 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-3' coro=<Connection._send_loop() running at /home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/telethon/network/connection/connection.py:322> wait_for=<Future pending cb=[Task.task_wakeup()]>>
2025-05-08 10:29:11,397 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-4' coro=<Connection._recv_loop() running at /home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/telethon/network/connection/connection.py:341> wait_for=<Future pending cb=[Task.task_wakeup()]>>
2025-05-08 10:29:12,410 - telethon.network.mtprotosender - INFO - Connecting to 149.154.167.92:443/TcpFull...
2025-05-08 10:29:12,513 - telethon.network.mtprotosender - INFO - Connection to 149.154.167.92:443/TcpFull complete!
2025-05-08 10:29:15,901 - __main__ - ERROR - Error validating session: Not a valid string
2025-05-08 10:29:23,694 - telethon.network.mtprotosender - INFO - Connecting to 149.154.167.92:443/TcpFull...
2025-05-08 10:29:23,797 - telethon.network.mtprotosender - INFO - Connection to 149.154.167.92:443/TcpFull complete!
2025-05-08 10:29:28,829 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-5' coro=<MTProtoSender._send_loop() running at /home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/telethon/network/mtprotosender.py:464> wait_for=<Future pending cb=[Task.task_wakeup()]>>
2025-05-08 10:29:28,829 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-6' coro=<MTProtoSender._recv_loop() running at /home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/telethon/network/mtprotosender.py:507> wait_for=<Future pending cb=[Task.task_wakeup()]>>
2025-05-08 10:29:28,829 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-3' coro=<Connection._send_loop() running at /home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/telethon/network/connection/connection.py:322> wait_for=<Future pending cb=[Task.task_wakeup()]>>
2025-05-08 10:29:28,830 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-4' coro=<Connection._recv_loop() running at /home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/telethon/network/connection/connection.py:341> wait_for=<Future pending cb=[Task.task_wakeup()]>>
2025-05-08 10:29:33,754 - telethon.network.mtprotosender - INFO - Connecting to 149.154.167.92:443/TcpFull...
2025-05-08 10:29:33,856 - telethon.network.mtprotosender - INFO - Connection to 149.154.167.92:443/TcpFull complete!
2025-05-08 10:29:38,901 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-5' coro=<MTProtoSender._send_loop() running at /home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/telethon/network/mtprotosender.py:464> wait_for=<Future pending cb=[Task.task_wakeup()]>>
2025-05-08 10:29:38,901 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-6' coro=<MTProtoSender._recv_loop() running at /home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/telethon/network/mtprotosender.py:507> wait_for=<Future pending cb=[Task.task_wakeup()]>>
2025-05-08 10:29:38,902 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-3' coro=<Connection._send_loop() running at /home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/telethon/network/connection/connection.py:322> wait_for=<Future pending cb=[Task.task_wakeup()]>>
2025-05-08 10:29:38,902 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-4' coro=<Connection._recv_loop() running at /home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/telethon/network/connection/connection.py:341> wait_for=<Future pending cb=[Task.task_wakeup()]>>
2025-05-08 10:29:53,589 - telethon.network.mtprotosender - INFO - Connecting to 149.154.167.92:443/TcpFull...
2025-05-08 10:29:53,693 - telethon.network.mtprotosender - INFO - Connection to 149.154.167.92:443/TcpFull complete!
2025-05-08 10:29:58,730 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-5' coro=<MTProtoSender._send_loop() running at /home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/telethon/network/mtprotosender.py:464> wait_for=<Future pending cb=[Task.task_wakeup()]>>
2025-05-08 10:29:58,731 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-6' coro=<MTProtoSender._recv_loop() running at /home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/telethon/network/mtprotosender.py:507> wait_for=<Future pending cb=[Task.task_wakeup()]>>
2025-05-08 10:29:58,731 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-3' coro=<Connection._send_loop() running at /home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/telethon/network/connection/connection.py:322> wait_for=<Future pending cb=[Task.task_wakeup()]>>
2025-05-08 10:29:58,731 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-4' coro=<Connection._recv_loop() running at /home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/telethon/network/connection/connection.py:341> wait_for=<Future pending cb=[Task.task_wakeup()]>>
2025-05-08 10:30:03,778 - telethon.network.mtprotosender - INFO - Connecting to 149.154.167.92:443/TcpFull...
2025-05-08 10:30:03,881 - telethon.network.mtprotosender - INFO - Connection to 149.154.167.92:443/TcpFull complete!
2025-05-08 10:30:08,910 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-5' coro=<MTProtoSender._send_loop() running at /home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/telethon/network/mtprotosender.py:464> wait_for=<Future pending cb=[Task.task_wakeup()]>>
2025-05-08 10:30:08,910 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-6' coro=<MTProtoSender._recv_loop() running at /home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/telethon/network/mtprotosender.py:507> wait_for=<Future pending cb=[Task.task_wakeup()]>>
2025-05-08 10:30:08,911 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-3' coro=<Connection._send_loop() running at /home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/telethon/network/connection/connection.py:322> wait_for=<Future pending cb=[Task.task_wakeup()]>>
2025-05-08 10:30:08,911 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-4' coro=<Connection._recv_loop() running at /home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/telethon/network/connection/connection.py:341> wait_for=<Future pending cb=[Task.task_wakeup()]>>
2025-05-08 10:30:14,428 - telethon.network.mtprotosender - INFO - Connecting to 149.154.167.92:443/TcpFull...
2025-05-08 10:30:14,530 - telethon.network.mtprotosender - INFO - Connection to 149.154.167.92:443/TcpFull complete!
2025-05-08 10:30:33,724 - telethon.network.mtprotosender - INFO - Connecting to 149.154.167.92:443/TcpFull...
2025-05-08 10:30:33,827 - telethon.network.mtprotosender - INFO - Connection to 149.154.167.92:443/TcpFull complete!
2025-05-08 10:30:38,857 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-5' coro=<MTProtoSender._send_loop() running at /home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/telethon/network/mtprotosender.py:464> wait_for=<Future pending cb=[Task.task_wakeup()]>>
2025-05-08 10:30:38,857 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-6' coro=<MTProtoSender._recv_loop() running at /home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/telethon/network/mtprotosender.py:507> wait_for=<Future pending cb=[Task.task_wakeup()]>>
2025-05-08 10:30:38,857 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-3' coro=<Connection._send_loop() running at /home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/telethon/network/connection/connection.py:322> wait_for=<Future pending cb=[Task.task_wakeup()]>>
2025-05-08 10:30:38,858 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-4' coro=<Connection._recv_loop() running at /home/runner/workspace/.pythonlibs/lib/python3.11/site-packages/telethon/network/connection/connection.py:341> wait_for=<Future pending cb=[Task.task_wakeup()]>>
